"""Build a windowed standalone AttendanceApp.exe.

Default: --onefile --noconsole so other PCs do not need Python or a _internal folder.
SQLite still lives next to the exe (processing.resources.writable_dir), never in _MEIPASS.

Usage (from D:\\chamcong):
    .\\.venv\\Scripts\\python.exe build.py
    .\\.venv\\Scripts\\python.exe build.py --onedir
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SPEC_ONEFILE = ROOT / "AttendanceApp.onefile.spec"
SPEC_ONEDIR = ROOT / "AttendanceApp.spec"


def _ctk_dir() -> Path:
    import customtkinter

    return Path(customtkinter.__file__).resolve().parent


def _write_onefile_spec() -> Path:
    ctk = _ctk_dir()
    # PyInstaller spec is Python; keep paths as raw strings for Windows.
    text = '''# -*- mode: python ; coding: utf-8 -*-
"""Generated by build.py — onefile + windowed CustomTkinter bundle."""

from pathlib import Path

from PyInstaller.utils.hooks import collect_all, collect_data_files, collect_submodules

datas = []
binaries = []
hiddenimports = [
    "pandas",
    "pandas._libs",
    "pandas.io.excel._openpyxl",
    "openpyxl",
    "openpyxl.cell._writer",
    "openpyxl.styles",
    "openpyxl.workbook",
    "tkcalendar",
    "tkcalendar.calendar",
    "tkcalendar.dateentry",
    "babel",
    "babel.numbers",
    "babel.dates",
    "babel.localtime",
    "babel.localedata",
    "sqlite3",
    "PIL._tkinter_finder",
    "tkinter",
    "customtkinter",
    "easyocr",
    "cv2",
    "correction_ui",
    "employee_ui",
    "holiday_ui",
    "leave_ui",
    "dashboard_ui",
    "history_ui",
    "date_picker",
    "tree_theme",
    "processing",
    "processing.ocr_processor",
    "processing.pipeline",
    "processing.validation",
    "processing.sessions",
    "processing.corrections",
    "processing.folders",
    "processing.master_data",
    "processing.excel_processor",
    "processing.merger",
    "processing.cong_rules",
    "processing.reports",
    "processing.report_k9",
    "processing.report_cham_cong",
    "processing.report_individual",
    "processing.period",
    "processing.output_files",
    "processing.utils",
    "processing.resources",
    "processing.database",
    "processing.holidays",
    "processing.leave",
    "processing.excel_locale",
    "processing.variance",
    "processing.history_import",
]

for pkg in ("customtkinter", "tkcalendar", "babel", "pandas", "openpyxl", "easyocr", "torch", "torchvision", "cv2"):
    try:
        pkg_datas, pkg_binaries, pkg_hidden = collect_all(pkg)
        datas += pkg_datas
        binaries += pkg_binaries
        hiddenimports += pkg_hidden
    except Exception:
        pass
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass

datas += collect_data_files("customtkinter")
datas += collect_data_files("babel")
datas.append((r"__CTK__", "customtkinter"))

easyocr_home = Path.home() / ".EasyOCR"
if easyocr_home.exists():
    datas.append((str(easyocr_home), ".EasyOCR"))

_spec_dir = Path(SPECPATH) if "SPECPATH" in dir() else Path(r"__ROOT__")
for _name in ("Template_Cham_Cong.xlsx", "K9 08.2026.xlsx"):
    _file = _spec_dir / _name
    if not _file.exists():
        raise SystemExit(f"Missing required bundled template: {_name}")
    datas.append((str(_file.resolve()), "."))
for _name in ("Mau_Cham_Cong.xlsx", "CHẤM CÔNG THÁNG 09.xlsx"):
    _file = _spec_dir / _name
    if _file.exists():
        datas.append((str(_file.resolve()), "."))

a = Analysis(
    ["app.py"],
    pathex=[r"__ROOT__"],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["pytest", "unittest"],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="AttendanceApp",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''
    SPEC_ONEFILE.write_text(
        text.replace("__CTK__", str(ctk)).replace("__ROOT__", str(ROOT)),
        encoding="utf-8",
    )
    return SPEC_ONEFILE


def _pyinstaller() -> Path:
    win = ROOT / ".venv" / "Scripts" / "pyinstaller.exe"
    nix = ROOT / ".venv" / "bin" / "pyinstaller"
    if win.exists():
        return win
    if nix.exists():
        return nix
    return Path(sys.executable).with_name("pyinstaller.exe" if os.name == "nt" else "pyinstaller")


def main() -> int:
    os.chdir(ROOT)
    onedir = "--onedir" in sys.argv
    exe = _pyinstaller()
    if onedir:
        spec = SPEC_ONEDIR
        print("Building onedir (dist\\AttendanceApp\\). Distribute the entire folder.")
    else:
        spec = _write_onefile_spec()
        print(f"CustomTkinter assets: {_ctk_dir()}")
        print("Building onefile windowed exe (dist\\AttendanceApp.exe).")
        print("First launch unpacks to a temp folder and can take a minute (EasyOCR/torch).")
        print("Database is created next to the exe (hr_system.db) — not inside _MEIPASS.")
    if not spec.exists():
        print(f"Missing spec: {spec}", file=sys.stderr)
        return 1
    cmd = [str(exe), "--noconfirm", str(spec)]
    if "--clean" in sys.argv:
        cmd.insert(1, "--clean")
    print(" ".join(cmd))
    return subprocess.call(cmd)


if __name__ == "__main__":
    raise SystemExit(main())
